config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy', as: 'logout'
  get  '/register', to: 'users#new',        as: 'new_user'
  post '/register', to: 'users#create'

  resources :users do
    resources :items do 
      member do
        post :toggle_complete
      end
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

	belongs_to :user

	validates :description, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :items

  has_secure_password validations: false

  validates :name, on: :create, length: {minimum: 2}
  validates :password, on: :create, length: {minimum: 5}
  validates_uniqueness_of :name

  def to_param
  	# This enables URL slugging because _path methods call the 
  	#  object model's 'to_param' method to get an :id for the URL.
  	#  I'm overriding that method and returning the name instead.
  	#  This ensures uniqueness because of the 'validates_uniqueness_of :name'
  	#  above.
  	self.name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user, :require_user

  def logged_in?
  	!!current_user
  end

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	else
  		nil
  	end
  end

  def require_user
  	access_denied('You have to be logged in to do that') unless logged_in?
  end

  def access_denied(message='Only the boss can do that...', redirect=root_path)
  	flash[:error] = message
  	redirect_to redirect
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :require_user
  before_action :find_item,     except: [:index, :new, :create]
  before_action :require_owner, except: [:index, :new, :create]

  def index
    # Get items and sort them in descending priority
    @items = current_user.items.where(completed: false).order(priority: :desc)
    @completed_items = current_user.items.where(completed: true).limit(3).order(updated_at: :desc)
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    @user = current_user
    @item.user_id = @user.id
    @item.completed = false

    if @item.save
      redirect_to user_items_path(current_user)
    else
      flash[:error] = "Oh snap! We couldn't save your item."
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      flash[:info] = "Your item was updated"
      redirect_to user_items_path(current_user)
    else
      flash[:error] = "Shucks...we couldn't update your item."
      render :edit
    end
  end

  def toggle_complete
    @item.completed = params[:completed]

    if !@item.save
      flash[:error] = "Snap! Something went wrong. Try it again..."
    end

    redirect_to user_items_path(current_user)
  end

  def destroy
    @item.destroy
    flash[:warning] = "Item deleted."
    redirect_to user_items_path(current_user)
  end

  private

  def item_params
    params.require(:item).permit([:description, :priority, :due_date])
  end

  def find_item
    begin
      @item = Item.find(params[:id])
    rescue
      redirect_to root_path
    end
  end

  def require_owner
    # owned_obj is some model object that has a 'user' attribute
    access_denied("You don't own that...") unless logged_in? and current_user == @item.user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(name: params[:user])
    if user and user.authenticate(params[:password])
      flash[:success] = "Welcome back #{user.name}!"
      session[:user_id] = user.id
      redirect_to user_items_path(user)
    else
      flash[:error] = "Something was wrong with your username or password"
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_user, except: [:new, :create]
	before_action :set_user, except: [:new, :create]

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	# Set the user role to 'user'
  	@user.role = 'user'

  	if @user.save
  		flash[:success] = "You've registered successfully!"
  		# Log the user in
  		session[:user_id] = @user.id
  		redirect_to user_items_path(@user)
  	else
  		flash.now[:error] = "Oh snap!  Something went wrong with your registration."
  		render action: "new"
  	end
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "Your profile was updated!"
  		redirect_to user_path(@user)
  	else
  		flash.now[:error] = "Oh snap!  Something went wrong updating your profile."
  		render :edit
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end

  def set_user
  	@user = current_user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # flash[:success] = "Test success!"
    # flash[:info] = "Test Info!"
    # flash[:warning] = "Test warning!"
    # flash[:error] = "Test danger!"
    if logged_in?
    	redirect_to user_items_path(current_user)
    end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<div>
  <%= form_for [current_user, @item], html: {class: "form-horizontal"} do |i| %>
    <div class="form-group">
      <%= i.label :description, "Description", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= i.text_field :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= i.label :priority, "Priority", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= i.text_field :priority, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= i.label :due_date, "Due Date", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= i.date_select :due_date, include_blank: true, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= i.submit (@item.new_record? ? "Add to List" : "Update"), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
 </div>

app/views/items/edit.html.erb
<div class="container">
	<h3>Edit Item</h3>
	<hr>
	<%= render 'layouts/errors', object: @item %>
	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<div class="container">

  <% if @items.size > 0 %>

    <h3>Your list</h3>
    <hr>
    <div class="table-responsive">
      <table class="table table-striped sortable">
        <tr>
          <th></th>
          <th>Description</th>
          <th>Priority</th>
          <th>Due</th>
        </tr>
        <% @items.each do |i| %>
          <tr>
            <td>
              <%= link_to toggle_complete_user_item_path(current_user, i, completed: :true), method: :post do %>
                <span class="glyphicon glyphicon-unchecked glyphicon-align-right" aria-hidden="true"></span>
              <% end %>
            </td>
            <td><%= link_to i.description, user_item_path(current_user, i) %></td>
            <td><%= i.priority %></td>
            <td><%= i.due_date %></td>
          </tr>
        <% end %>
      </table>
    </div>

  <% else %>

    <h3 class="text-center">You don't have anything in your list yet.</h3>
    <p class="text-center">Click the "New Item" button above to get started.</p>

  <% end %>


  <% if @completed_items.size > 0 %>

    <hr>

    <h5 class="completed">Completed Items...</h5>
    <div class="table-responsive">
      <table class="table table-striped">
        <% @completed_items.each do |i| %>
          <tr>
            <td>
              <%= link_to toggle_complete_user_item_path(current_user, i, completed: :false), class: "completed", method: :post do %>
                <span class="glyphicon glyphicon-check glyphicon-align-right" aria-hidden="true"></span>
              <% end %>
            </td>
            <td class="completed"><%= i.description %></td>
            <td class="completed"><%= i.priority %></td>
            <td class="completed"><%= i.due_date %></td>
          </tr>
        <% end %>
      </table>
    </div>

  <% end %>

</div>

app/views/items/new.html.erb
<div class="container">
	<h3>Add a new item</h3>
	<hr>
	<%= render 'layouts/errors', object: @item %>
	<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="container">
	<div><%= link_to "Edit Item", edit_user_item_path(current_user, @item) %></div>
	<hr>
	<dl class="dl-horizontal">
		<dt>Description</dt>
		<dd><%= @item.description %></dd>
		<dt>Priority</dt>
		<dd><%= @item.priority %></dd>
		<dt>Due Date</dt>
		<dd><%= @item.due_date %></dd>
		<dt>Status</dt>
		<dd><%= @item.completed ? "Complete" : "Incomplete" %></dd>
	</dl>
	<hr>
	<%= button_to "Delete Item", user_item_path(current_user, @item), class: 'btn btn-danger pull-right', method: :delete %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h5>Please fix the following errors:</h5>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% case name %>
    <% when "success" %>
      <% alert_type = "success" %>
    <% when "info" %>
      <% alert_type = "info" %>
    <% when "warning" %>
      <% alert_type = "warning" %>
    <% when "error" %>
      <% alert_type = "danger" %>
    <% else %>
      <% alert_type = "info" %>
  <% end %>
  <div class='alert alert-<%="#{alert_type}"%> alert-dismissable' role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= "<strong>#{name.capitalize}:</strong>  #{msg}".html_safe %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Simple List</title>
  <meta name="description" content="A Simple List App">
  <meta name="author" content="Travis Riggs">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if logged_in? %>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <%= link_to "Simple List", user_items_path(current_user), class: "navbar-brand" %> 
        </div>
      
        <%= link_to new_user_item_path(current_user), class: "btn btn-success btn-sm navbar-btn btn-right-pad" do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Item
        <% end %>

        <div class="btn-group">
          <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'View Profile', user_path(current_user) %></li>
            <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          </ul>
        </div>

      </div>
    </div>
  <% end %>

  <% if logged_in? %>
    <div class="navbar-padding">
      <div class="container">
        <%= render 'layouts/messages' %>
      </div>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div>
  <%= form_for @user, html: {class: "form-horizontal"} do |u| %>
    <div class="form-group">
      <%= u.label :name, "Username", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= u.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= u.label :email, "Email", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= u.text_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= u.label :password, "Password", class: "col-sm-2 col-sm-offset-2 control-label" %>
      <div class="col-sm-6">
        <%= u.password_field :password, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= u.submit (@current_user ? "Update" : "Register"), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
 </div>

app/views/users/edit.html.erb
<div class="container">
	<h3>Update your profile</h3>
	<hr>
	<%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
	<h3>Please Register</h3>
	<hr>
	<%= render 'layouts/errors', object: @user %>
	<%= render 'form' %>
</div>

app/views/users/show.html.haml
.container

	%h3= "Profile: #{@current_user.name}"
	%hr

	.well
		%dl.dl-horizontal.no-bottom-padding
			%dt Username:
			%dd= @user.name
			%dt Email:
			%dd= @user.email

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Simple List!</h1>
  <div class="container">
    <p>Simple list is a simple app that allows you to create a list and access it from any device.  You can make it a to-do list, a grocery list or really anything else that you want.</p>
  </div>
</div>

<div class="container">
  <%= render 'layouts/messages' %>
</div>

<div class="container">
  <!--   <p class="lead"> Please Log in </p>
  <hr> -->
  <div>
    <%= form_tag login_path, class: "form-horizontal" do %>
      <div class="form-group">
        <%= label_tag :user, "Username", class: "col-sm-2 col-sm-offset-2 control-label" %>
        <div class="col-sm-6">
          <%= text_field_tag :user, params[:user] || "", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag :password, "Password", class: "col-sm-2 col-sm-offset-2 control-label" %>
        <div class="col-sm-6">
          <%= password_field_tag :password, params[:password] || "", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-10">
          <%= submit_tag "Login", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>

  <hr>

  <h3 class="text-center">New user?</h3>
  <%= button_to "Register", register_path, class: "btn btn-success center-block", method: :get %>
  <!-- <button class="btn btn-success center-block">Register</button> -->

</div>